/* YV_kmerhist - this program takes a histogram generated by KMC and output the histogram of counts
 */

#include "kmer_DB.h"
int main(int argc, char *argv[]) {
	string v1(argv[1]);
	string v2(argv[2]);
	Kmer_DB acc_kmers(v1,v2);
	vector<std::size_t> counters = acc_kmers.calculate_kmers_counts_histogram();
	
	for(std::size_t i=0; i<counters.size(); i++) {
		cout << i << "\t" << counters[i] << endl;											
	}

	return 0;
}
//}

